### ISSUE TITLE
How to populate-db command execute in Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by Devansh3790** [angular-university/angular-firebase-app-starter#2]
I try to populate firebase app. I am beginner don't have experience in Angular2 and firebase, Thanks

**Comment by Marcamillian** [comment]
Hi Devansh,

Am I right in thinking that you are receiving an error in relation to having access to the database?

I think you might need to update the file that is providing the config for the firebase database that you are trying to update.

In the populate-db.ts file it imports a firebase.config file at the top

`import {database, initializeApp} from "firebase";`
`import {firebaseConfig} from "./src/environments/firebase.config";`
`import {dbData} from "./db-data";`


If we open the file in **src/environments** the we can change the exported "firebaseConfig" object to point to your firebase database by putting in information from the firebase console

![image](https://cloud.githubusercontent.com/assets/3187001/22035208/0affc0ec-dce7-11e6-88f7-a3899065f73c.png)

![image](https://cloud.githubusercontent.com/assets/3187001/22035249/2f34f02c-dce7-11e6-96e4-fb02fdf56255.png)

**Comment by jhades** [comment]
Hello @Marcamillian, thank you for the detailed response, I think you're right that is the correct solution. I'm closing the issue, @Devansh3790  if the problem still remains after applying @Marcamillian  solution please let us know. Thanks, Kind Regards, Vasco
